### ISSUE TITLE
需要多大的显存 1080ti 爆显存了

### ISSUE THREAD

**Issue by SomeoneNotLikeYou** [z814081807/DeepNER#12]
RuntimeError: CUDA out of memory. Tried to allocate 384.00 MiB (GPU 0; 11.00 GiB total capacity; 9.52 GiB already allocated; 124.50 MiB free; 9.54 GiB reserved in total by PyTorch)

**Comment by z814081807** [comment]
> RuntimeError: CUDA out of memory. Tried to allocate 384.00 MiB (GPU 0; 11.00 GiB total capacity; 9.52 GiB already allocated; 124.50 MiB free; 9.54 GiB reserved in total by PyTorch)

尝试调小batch_size
