### ISSUE TITLE
构建实体知识库

### ISSUE THREAD

**Issue by penghui-pwld-two** [z814081807/DeepNER#15]
我想问一下构建实体知识库的作用是什么？ 感谢

**Comment by z814081807** [comment]
> 我想问一下构建实体知识库的作用是什么？ 感谢

就是利用训练集标注的实体信息，构造一个实体字典。

**Comment by penghui-pwld-two** [comment]
感谢您的回复 利用全部的标注数据构造实体字典 具体是如何训练的 非常感谢

**Comment by z814081807** [comment]
> 感谢您的回复 利用全部的标注数据构造实体字典 具体是如何训练的 非常感谢

这个字典从训练集里面很容易构造出来。构造完成之后不需要参与训练，可以直接用这个实体词典去匹配文本，找到文本里面的实体，这是最早NER的做法。这里构造字典的目的是模型预测完之后再用字典匹配一下，可以补充那些模型没预测出来的实体。

**Comment by penghui-pwld-two** [comment]
感谢 感谢 非常感谢 penghuipwld ***@***.*** 签名由 网易邮箱大师 定制 在2021年04月26日 17:18，zxx飞翔的鱼 写道： 感谢您的回复 利用全部的标注数据构造实体字典 具体是如何训练的 非常感谢 这个字典从训练集里面很容易构造出来。构造完成之后不需要参与训练，可以直接用这个实体词典去匹配文本，找到文本里面的实体，这是最早NER的做法。这里构造字典的目的是模型预测完之后再用字典匹配一下，可以补充那些模型没预测出来的实体。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by topDreamer** [comment]
您好！请问这个实体知识库在模型预测后使用（直接进行检索匹配）的话，是不是会造成高召回、低准确的问题呢？就比如一个实体有多个类型，那么在匹配的时候是如何选择给定哪种类型呢？如何避免这种问题？
