### ISSUE TITLE
我想问问这个报错怎么回事

### ISSUE THREAD

**Issue by cc846049716** [z814081807/DeepNER#18]
> 这个文件确实在，但是就是报错出不来。大佬帮我看一下吧
![QQ图片20210512121006](https://user-images.githubusercontent.com/84059638/117917795-6fbc4e00-b31c-11eb-9195-f60be22bd996.png)

**Comment by z814081807** [comment]
> > 这个文件确实在，但是就是报错出不来。大佬帮我看一下吧
> > ![QQ图片20210512121006](https://user-images.githubusercontent.com/84059638/117917795-6fbc4e00-b31c-11eb-9195-f60be22bd996.png)

路径没写对，仔细看看

**Comment by cc846049716** [comment]
大佬呀，我是萌新这句话有点不懂。也不是不懂，就是没法理解。这里面99个unused转哪两个。我不知道是不是我理解有误，是随机的两个吗？
![QQ图片20210512150200](https://user-images.githubusercontent.com/84059638/117932520-08f65f00-b333-11eb-9a30-d3036f15643e.png)

**Comment by z814081807** [comment]
> 大佬呀，我是萌新这句话有点不懂。也不是不懂，就是没法理解。这里面99个unused转哪两个。我不知道是不是我理解有误，是随机的两个吗？
> ![QQ图片20210512150200](https://user-images.githubusercontent.com/84059638/117932520-08f65f00-b333-11eb-9a30-d3036f15643e.png)

都可以，替换前两个就行。
