### ISSUE TITLE
pseudo数据是什么意思，是远程监督得到的吗

### ISSUE THREAD

**Issue by macheng6** [z814081807/DeepNER#21]

**Comment by z814081807** [comment]
> _No description provided._
是伪标签，通过模型对未标注的样本进行预测得到的

**Comment by macheng6** [comment]
> > _No description provided._
> > 是伪标签，通过模型对未标注的样本进行预测得到的

candidate entities是什么含义呢？

**Comment by z814081807** [comment]
> > > _No description provided._
> > > 是伪标签，通过模型对未标注的样本进行预测得到的
> 
> candidate entities是什么含义呢？

那个远程监督得到的，实际没用上，可以去掉
