### ISSUE TITLE
bert/torch_roberta_wwm放的是哪个预训练模型文件

### ISSUE THREAD

**Issue by tianke0711** [z814081807/DeepNER#22]
我想问一下这个注意具体指的是哪个训练模型的 （torch_roberta_wwm, uer_large?）（注意：需人工将 vocab.txt 中两个 [unused] 转换成 [INV] 和 [BLANK]）

**Comment by tianke0711** [comment]
我想问一下这个注意具体指的是哪个训练模型的 （torch_roberta_wwm, uer_large?）（注意：需人工将 vocab.txt 中两个 [unused] 转换成 [INV] 和 [BLANK]）

**Comment by z814081807** [comment]
> 我想问一下这个注意具体指的是哪个训练模型的 （torch_roberta_wwm, uer_large?）（注意：需人工将 vocab.txt 中两个 [unused] 转换成 [INV] 和 [BLANK]）

都需要改，有的改过了就不用改，数据处理tokenizer需要

**Comment by TinaGioro** [comment]
你好，请问目录out/final和out/stack都发一下吗

**Comment by TinaGioro** [comment]
还有我想请问下“需人工将 vocab.txt 中两个 [unused] 转换成 [INV] 和 [BLANK]）” 是指的是人工选定[unused]的位置更改吗

**Comment by TinaGioro** [comment]
还有想请问下您们模型使用的chinese_bert_wwm是哪个版本的啊，我下载的是chinese_wwm_pytorch貌似不太对。大神大佬求助下，菜鸟程序媛在此跪谢了！
