### ISSUE TITLE
评价指标

### ISSUE THREAD

**Issue by macheng6** [z814081807/DeepNER#24]
代码里的评价指标是计算了每一类的F1之后按照类别加权平均了，这是microF1吗？
microF1不应该是统计所有样本的tp,fp,fn然后再算吗？

**Comment by z814081807** [comment]
> 代码里的评价指标是计算了每一类的F1之后按照类别加权平均了，这是microF1吗？
> microF1不应该是统计所有样本的tp,fp,fn然后再算吗？

两者等价 你可以去查一下

**Comment by macheng6** [comment]
> > 代码里的评价指标是计算了每一类的F1之后按照类别加权平均了，这是microF1吗？
> > microF1不应该是统计所有样本的tp,fp,fn然后再算吗？
> 
> 两者等价 你可以去查一下

谢谢回答，还有一个问题，bert+span我没有看太懂，有相关的论文可以分享吗？

**Comment by z814081807** [comment]
> > > 代码里的评价指标是计算了每一类的F1之后按照类别加权平均了，这是microF1吗？
> > > microF1不应该是统计所有样本的tp,fp,fn然后再算吗？
> > 
> > 
> > 两者等价 你可以去查一下
> 
> 谢谢回答，还有一个问题，bert+span我没有看太懂，有相关的论文可以分享吗？

https://www.kexue.fm/archives/5409 看一下这篇文章
