### ISSUE TITLE
请问Uer-large（24层）是Modelzoo中的哪一个模型？

### ISSUE THREAD

**Issue by JunnYu** [z814081807/DeepNER#26]
请问请问Uer-large（24层）是这当中的哪一个https://github.com/dbiir/UER-py/wiki/Modelzoo，谢谢

**Comment by z814081807** [comment]
> 请问请问Uer-large（24层）是这当中的哪一个[https://github.com/dbiir/UER-py/wiki/Modelzoo，谢谢](https://github.com/dbiir/UER-py/wiki/Modelzoo%EF%BC%8C%E8%B0%A2%E8%B0%A2)

用的bert-large好像，记不清了，这个其实和哈工大那个roberta-large差不多，后续用这套代码打别的比赛用的哈工大那个

**Comment by JunnYu** [comment]
找到了是这个权重，
https://github.com/dbiir/UER-py/wiki/Modelzoo
MixedCorpus+BertEncoder(large)+MlmTarget 
https://share.weiyun.com/5G90sMJ
Pre-trained on mixed large Chinese corpus. The configuration file is bert_large_config.json

**Comment by jzsbioinfo** [comment]
但是这个没有提供vocab文件呀？ 没有词汇表怎么分词。。。
