### ISSUE TITLE
复赛的dockerfile

### ISSUE THREAD

**Issue by Power886** [z814081807/DeepNER#27]
能不能提供一下复赛的dockerfile格式

**Comment by z814081807** [comment]
> 能不能提供一下复赛的dockerfile格式

## 从NER基础镜像构建  自己配一个镜像
FROM registry.cn-shenzhen.aliyuncs.com/zxxfeiyu/zxx_tianchi_ner:base

## 把当前文件夹里的文件构建到镜像的根目录下
ADD . /

## 指定默认工作目录为根目录（需要把run.sh和生成的结果文件都放在该文件夹下，提交后才能运行）
WORKDIR /

## 镜像启动后统一执行 sh run.sh
CMD ["sh", "run.sh"]
