### ISSUE TITLE
param distant_labels: 远程监督 label

### ISSUE THREAD

**Issue by bestpredicts** [z814081807/DeepNER#3]
这个distant_labels: 远程监督 label  没理解这个什么意思 ？ 能解释一下嘛

**Comment by z814081807** [comment]
> 这个distant_labels: 远程监督 label 没理解这个什么意思 ？ 能解释一下嘛

这个实际代码里没用 ， 远程监督label简单点理解就是根据现有的标注label形成字典，下次预测时直接匹配字典
