### ISSUE TITLE
训练和预测不一致问题

### ISSUE THREAD

**Issue by kevinuserdd** [z814081807/DeepNER#30]
mrc方法中的问题
1. 训练时候构造query+context作为输入； 但是你预测时候就是context作为输入；
2. 预测代码np.argmax()是多分类吧，那你一句话里面只能出现一个实体吗？

**Comment by z814081807** [comment]
> mrc方法中的问题
> 
> 1. 训练时候构造query+context作为输入； 但是你预测时候就是context作为输入；
> 2. 预测代码np.argmax()是多分类吧，那你一句话里面只能出现一个实体吗？

预测的时候需要补充query 13类预测13次 我代码里没上传mrc单独预测的代码；至于为什么是argmax 请仔细看mrc方法的原理
