### ISSUE TITLE
loss不收敛

### ISSUE THREAD

**Issue by taojingcong** [z814081807/DeepNER#31]
Loss优化到一定程度后突然上升, 一直上升到几万, 可能是什么原因呢.(没有修改代码)

**Comment by taojingcong** [comment]
跑stack任务, 用crf和mrc模型都有这个问题

**Comment by CocoZzzzz** [comment]
我也遇到同样的问题了，没有修改代码，请问下你解决了么？

**Comment by taojingcong** [comment]
还没有...

**Comment by taojingcong** [comment]
> 我也遇到同样的问题了，没有修改代码，请问下你解决了么？
还没有...

**Comment by taojingcong** [comment]
> 我也遇到同样的问题了，没有修改代码，请问下你解决了么？

还没有,

**Comment by z814081807** [comment]
> > 我也遇到同样的问题了，没有修改代码，请问下你解决了么？
> 
> 还没有,

参考关闭的Issues里：Why the total loss increase suddenly and rapidly when training the base crf

**Comment by z814081807** [comment]
> 我也遇到同样的问题了，没有修改代码，请问下你解决了么？

参考关闭的Issues里：Why the total loss increase suddenly and rapidly when training the base crf

**Comment by CocoZzzzz** [comment]
> > 我也遇到同样的问题了，没有修改代码，请问下你解决了么？
> 
> 参考关闭的Issues里：Why the total loss increase suddenly and rapidly when training the base crf

解决了，谢谢！
