### ISSUE TITLE
No such file or directory: '../../data/raw_data/train/0.txt'

### ISSUE THREAD

**Issue by xiaoguzai** [z814081807/DeepNER#32]
求助大佬
/src/preprocess中执行
python convert_raw_data.py会报错
No such file or directory: '../../data/raw_data/train/0.txt'
怎么解决

**Comment by z814081807** [comment]
> 求助大佬
> /src/preprocess中执行
> python convert_raw_data.py会报错
> No such file or directory: '../../data/raw_data/train/0.txt'
> 怎么解决

这个不用执行了，已提供转换好的数据 无需运行
