### ISSUE TITLE
pseudo_nums == 0或1的问题

### ISSUE THREAD

**Issue by xiaoguzai** [z814081807/DeepNER#34]
看大佬的代码中，如果pseudo_nums == 1的时候训练速度好像慢一点，想问下大佬pseudo_nums 的值为0还是为1是如何确定的？

**Comment by z814081807** [comment]
> 看大佬的代码中，如果pseudo_nums == 1的时候训练速度好像慢一点，想问下大佬pseudo_nums 的值为0还是为1是如何确定的？

0表示正常样本 1表示伪标签样本 用了半监督的思想； 正常训练不使用半监督学习让pseudo=None就可以
