### ISSUE TITLE
关于pytorch-crf

### ISSUE THREAD

**Issue by jxlin98** [z814081807/DeepNER#36]
我在其他序列标注任务使用pytorch-crf时发现训练速度明显变慢（相比于简单使用softmax，训练时间几乎翻倍），请问你们在使用pytorch-crf时遇到过这种情况吗

**Comment by z814081807** [comment]
> 我在其他序列标注任务使用pytorch-crf时发现训练速度明显变慢（相比于简单使用softmax，训练时间几乎翻倍），请问你们在使用pytorch-crf时遇到过这种情况吗

crf一般效果比softmax好很多， 他是机器学习的方法，会慢很多(crf在推理时有优化的方式可以快很多)； span方法会比softmax快很多,效果还不错
