### ISSUE TITLE
请问MRC代码可以做嵌套命名实体识别吗

### ISSUE THREAD

**Issue by lyyFromSwust** [z814081807/DeepNER#38]
我把自己的带有嵌套的数据转为相应的格式，使用MRC那一块进行训练，发现出来的效果F1有67，但是并不知道这个MRC能否处理嵌套情况？另外如果想要做嵌套命名实体识别，有没有大佬对代码进行改进的呢

**Comment by z814081807** [comment]
> 名实体识别，有没有大佬对代码进行改进的呢

本项目实现的MRC无法处理嵌套情况，原因在于解码部分的策略是严格解码，原论文是可以处理嵌套情况的。
嵌套NER相关参考如下，有具体代码实现：
1.https://zhuanlan.zhihu.com/p/326302618?utm_source=wechat_session&utm_medium=social&utm_oi=52706551005184&utm_content=group3_article&utm_campaign=shareopn&s_r=0
2.https://kexue.fm/archives/8373
3.https://mp.weixin.qq.com/s/G3qR6BD1pp5EzIxSoueJSQ

**Comment by liuweishuo** [comment]
想问下项目中用的严格编码是不是会导致出现多个start对应一个end的情况？
