### ISSUE TITLE
把batch_size调成6 F1值只有0.13了

### ISSUE THREAD

**Issue by tecmry** [z814081807/DeepNER#4]
In step 272:
 [MIRCO] precision: 0.0000, recall: 0.0000, f1: 0.0000

In step 544:
 [MIRCO] precision: 0.2668, recall: 0.0088, f1: 0.0160

In step 816:
 [MIRCO] precision: 0.3403, recall: 0.0183, f1: 0.0340

In step 1088:
 [MIRCO] precision: 0.3746, recall: 0.0263, f1: 0.0487

In step 1360:
 [MIRCO] precision: 0.3832, recall: 0.0597, f1: 0.0994

In step 1632:
 [MIRCO] precision: 0.3413, recall: 0.0727, f1: 0.1162

In step 1904:
 [MIRCO] precision: 0.2666, recall: 0.0772, f1: 0.1148

In step 2176:
 [MIRCO] precision: 0.2869, recall: 0.0841, f1: 0.1250

In step 2448:
 [MIRCO] precision: 0.2785, recall: 0.0944, f1: 0.1365

In step 2720:
 [MIRCO] precision: 0.2690, recall: 0.0906, f1: 0.1314

In step 100000:
 [MIRCO] precision: 0.2824, recall: 0.0845, f1: 0.1260

Max f1 is: 0.1364805133924134, in step 2448

这是我跑出来的结果，除了没有修改vocab.txt里的uncase其他设置都没变，batch_size24直接oom了。

**Comment by z814081807** [comment]
> In step 272:
> [MIRCO] precision: 0.0000, recall: 0.0000, f1: 0.0000
> 
> In step 544:
> [MIRCO] precision: 0.2668, recall: 0.0088, f1: 0.0160
> 
> In step 816:
> [MIRCO] precision: 0.3403, recall: 0.0183, f1: 0.0340
> 
> In step 1088:
> [MIRCO] precision: 0.3746, recall: 0.0263, f1: 0.0487
> 
> In step 1360:
> [MIRCO] precision: 0.3832, recall: 0.0597, f1: 0.0994
> 
> In step 1632:
> [MIRCO] precision: 0.3413, recall: 0.0727, f1: 0.1162
> 
> In step 1904:
> [MIRCO] precision: 0.2666, recall: 0.0772, f1: 0.1148
> 
> In step 2176:
> [MIRCO] precision: 0.2869, recall: 0.0841, f1: 0.1250
> 
> In step 2448:
> [MIRCO] precision: 0.2785, recall: 0.0944, f1: 0.1365
> 
> In step 2720:
> [MIRCO] precision: 0.2690, recall: 0.0906, f1: 0.1314
> 
> In step 100000:
> [MIRCO] precision: 0.2824, recall: 0.0845, f1: 0.1260
> 
> Max f1 is: 0.1364805133924134, in step 2448
> 
> 这是我跑出来的结果，除了没有修改vocab.txt里的uncase其他设置都没变，batch_size24直接oom了。

看一下是不是transformer版本的问题 有没有什么warning 应该哪里出了问题

**Comment by tecmry** [comment]
不好意思 是transformer的版本问题 谢谢了
