### ISSUE TITLE
（注意：需人工将 vocab.txt 中两个 [unused] 转换成 [INV] 和 [BLANK]） 刚开始参加nlp比赛不太懂这句话什么意思。

### ISSUE THREAD

**Issue by Torres9999** [z814081807/DeepNER#40]
我下载了 百度云的模型，
观察了 uer_roberta-large. vocab.TXT 和roberta-wwm的vocab.TXT 的前几行 ，您的意思是把roberta-wwmz中的开始出现的两行unused替换成  和uer_roberta vocab中一样的格式吗。
![image](https://user-images.githubusercontent.com/77044336/159207293-afb00cf9-e407-4a97-bf50-94ccd5690592.png)
![image](https://user-images.githubusercontent.com/77044336/159207303-4d76dfce-fde6-41ae-8c9c-df93a47a447e.png)

**Comment by z814081807** [comment]
> 我下载了 百度云的模型， 观察了 uer_roberta-large. vocab.TXT 和roberta-wwm的vocab.TXT 的前几行 ，您的意思是把roberta-wwmz中的开始出现的两行unused替换成 和uer_roberta vocab中一样的格式吗。 ![image](https://user-images.githubusercontent.com/77044336/159207293-afb00cf9-e407-4a97-bf50-94ccd5690592.png) ![image](https://user-images.githubusercontent.com/77044336/159207303-4d76dfce-fde6-41ae-8c9c-df93a47a447e.png)

对的 有的没替换手动替换就行

**Comment by z814081807** [comment]
> 我下载了 百度云的模型， 观察了 uer_roberta-large. vocab.TXT 和roberta-wwm的vocab.TXT 的前几行 ，您的意思是把roberta-wwmz中的开始出现的两行unused替换成 和uer_roberta vocab中一样的格式吗。 ![image](https://user-images.githubusercontent.com/77044336/159207293-afb00cf9-e407-4a97-bf50-94ccd5690592.png) ![image](https://user-images.githubusercontent.com/77044336/159207303-4d76dfce-fde6-41ae-8c9c-df93a47a447e.png)

可以参考closed issues 中 词汇表的回答
