### ISSUE TITLE
span解码

### ISSUE THREAD

**Issue by liuweishuo** [z814081807/DeepNER#41]
您好 我看到readme中提到span解码过程中使用的是严格编码过程 嵌套得实体取概率最大的 我在解码代码中看到还是可能出现一个end对应多个start的情况。

**Comment by z814081807** [comment]
> 您好 我看到readme中提到span解码过程中使用的是严格编码过程 嵌套得实体取概率最大的 我在解码代码中看到还是可能出现一个end对应多个start的情况。

可能会出现，比较少，如果相完全不出现可以加个判断代码 :   新的start i   > 上一个 end j

**Comment by liuweishuo** [comment]
“采用严格解码形式，重叠实体选取logits最大的一个，保证准确率” 这部分不太理解是怎么选取logits最大的一个 而且还是会出现“B-1 B-2 E-2 E-1”的嵌套情况啊

**Comment by z814081807** [comment]
> “采用严格解码形式，重叠实体选取logits最大的一个，保证准确率” 这部分不太理解是怎么选取logits最大的一个 而且还是会出现“B-1 B-2 E-2 E-1”的嵌套情况啊

这里的说明不严谨了。 要处理这种情况，需要根据start 和 end 判断是否出现嵌套， 出现了 再根据他们的logits 取大的  这个是解码出来最终的后处理，代码里面没有

**Comment by liuweishuo** [comment]
啊啊 明白了 感谢
