### ISSUE TITLE
RuntimeError: expected device cuda:2 and dtype Float but got device cuda:2 and dtype Long

### ISSUE THREAD

**Issue by penghui-pwld-two** [z814081807/DeepNER#8]
您好，很感谢您分享的程序，我（小白）在运行的时候出现如下错误，请问如何解决：
RuntimeError: expected device cuda:2 and dtype Float but got device cuda:2 and dtype Long

非常感谢您！

**Comment by z814081807** [comment]
> 您好，很感谢您分享的程序，我（小白）在运行的时候出现如下错误，请问如何解决：
> RuntimeError: expected device cuda:2 and dtype Float but got device cuda:2 and dtype Long
> 
> 非常感谢您！

pytorch 版本问题应该
