### ISSUE TITLE
> 您好，很感谢您分享的程序，我（小白）在运行的时候出现如下错误，请问如何解决：

### ISSUE THREAD

**Issue by penghui-pwld-two** [z814081807/DeepNER#9]
> 您好，很感谢您分享的程序，我（小白）在运行的时候出现如下错误，请问如何解决：
> RuntimeError: expected device cuda:2 and dtype Float but got device cuda:2 and dtype Long
> 
> 非常感谢您！

pytorch 版本问题应该

_Originally posted by @z814081807 in https://github.com/z814081807/DeepNER/issues/8#issuecomment-806416634_

**Comment by penghui-pwld-two** [comment]
非常感谢您的回复  我的pytorch==1.2.0 我尝试了 pytorch==1.1.0和1.3.1都不行，如果您方便可以告诉我下您使用的版本吗，再次感谢

**Comment by z814081807** [comment]
> 非常感谢您的回复 我的pytorch==1.2.0 我尝试了 pytorch==1.1.0和1.3.1都不行，如果您方便可以告诉我下您使用的版本吗，再次感谢

1.6 +
